[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    olikraus/U8g2 @ ^2.34.15
    majicdesigns/MD_MAX72XX @ ^3.5.1
    bblanchon/ArduinoJson @ ^6.21.3
    arduino-libraries/NTPClient @ ^3.2.1
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    Links2004/WebSockets @ ^2.4.1
